### ISSUE TITLE
CudaAllreduceHalvingDoubling writev error 

### ISSUE THREAD

**Issue by sergey-serebryakov** [facebookincubator/gloo#34] opened 2017-05-02 20:56 UTC
Hi! This a duplicate post from Caffe2 github page. This is my original [question](https://github.com/caffe2/caffe2/issues/450). I think that this [thread](https://github.com/caffe2/caffe2/issues/476) may also relate to the problem or incorrect software/hardware setup.
The error is `Write must always succeed in sync mode` in Pair::write. This was a quick investigation:
> There's something wrong with my hardware/software setup I cannot figure out. I tried to run resnet50_trainer.py (no modifications) on single (2xK-80) and multiple nodes with REDIS rendezvous. It fails. In single device mode (num_shards=1 ) it works OK.
It fails (soon after it has started) performing CudaAllReduceHalvingDoubling Gloo operation (transport - TCP). The method that fails is Pair::write in Gloo library. It turns out at some point in time, it wants to send 4096040 bytes, waits for some time (sending??? - here something is wrong), and returning from writev call with number of bytes sent = 1376004. The call to Pair::write that fails is not the first one. Some previous calls work correct.
Could you guys guide me what should I pay attention to to resolve it.
Thanks!
PS: This is what works OK:
Caffe and Caffe2 run OK on 1, 2 and 4 GPUs (data parallel schema).
p2pBandwidthTest from CUDA samples runs OK.
Benchmarks from Gloo library run OK.
Firewalls are disabled.

I am planning to dig into this issue this weekend but maybe you know what the cause is or maybe you can give me a hint from where to start.
Thanks!

**Comment by pietern** [comment] 2017-05-02 21:15
Thanks for reporting!

We made an assumption the entire write can be done in one shot since we size the OS level send buffers before doing the write. The short write happening likely means this doesn't work as expected and your OS probably doesn't grow this connection's TCP buffers over 1376004 bytes. I thought doing blocking writes would still drain this buffer until the entire write was completed, but apparently not. We can easily change this to do what you suggest and keep looping if nwritten < nbytes and the pair is in sync mode.

Do you want to give this a shot yourself?

**Comment by sergey-serebryakov** [comment] 2017-05-02 21:32
Thanks. 
I was thinking exactly about this reason. I will explore in more details what's happening in my system, will modify the code, run tests and report results. Just to make sure I can run distributed Caffe2 and this is the reason it fails now. I think from there it'll be clear if it's something worth adding to current version.

**Comment by pietern** [comment] 2017-05-02 21:34
The machines I'm testing on have high thresholds, so it's possible we never hit this case before:

```
# cat /proc/sys/net/ipv4/tcp_mem
6170274 8227033 12340548
```

**Comment by sergey-serebryakov** [comment] 2017-05-02 21:48
My numbers are 3084294 4112392 6168588. And two processes still send each other only 1376004 bytes. BTW, it takes some time (10 or so seconds) before `writev` returns with these results.

**Comment by talk2ap001** [comment] 2017-05-03 06:02
I'm facing the same error. You can check the last comment on https://github.com/caffe2/caffe2/issues/360
`what():  [enforce fail at /nfs/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:691] rv. Write must always succeed in sync mode`

**Comment by sergey-serebryakov** [comment] 2017-05-03 07:23
Maybe buffer size has nothing to do with the issue. I noticed that some first `writev` calls during very first mini batch work fine even with large data being sent between workers. The call that fails actually returns by a timeout that is set to be 30 secs. I added some small changes that adjust data pointers based on number of bytes actually sent and resends the remaining part of the data. This second call immediately returns with errno equal to `EAGAIN` (try again).

**Comment by pietern** [comment] 2017-05-03 20:00
@sergey-serebryakov So the write itself times out? AFAICT this means the kernel can't flush its TCP buffer, which means the other process isn't doing any reads (when in sync mode)... We should be marking the pair as timed out in this case, instead of only returning false from the write function.

The allreduce operations inserted into the graph by `data_parallel_model` in Caffe2 include a partial ordering such that different processes run the different allreduce operations in the same order. This makes me think that something else is going on... What happens on the other machine when you see this timeout?

**Comment by sergey-serebryakov** [comment] 2017-05-03 20:32
@pietern The machines, or more precisely, different processes within one muti-GPU machine, seems to be doing same thing - they try to send same amount of data to each other. I will attach logs of send/recv calls later today. 
I am sorry for not providing detailed description. I will really be able to investigate it this weekend.

**Comment by pietern** [comment] 2017-05-03 20:33
@sergey-serebryakov Thanks for your investigation!

I have a patch incoming that will treat this condition correctly as timeout.

**Comment by pietern** [comment] 2017-05-03 21:56
With this latest patch the error will be treated as timeout if it actually is one. Appreciate you testing it out!

**Comment by talk2ap001** [comment] 2017-05-04 07:41
It gives timeout error:
```
INFO:resnet50_trainer:Starting epoch 0/1000
terminate called after throwing an instance of 'gloo::IoException'
  what():  [/nfs/AMBUJ/Caffe2_LatestGLOO5/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:279] Write timeout [172.17.27.12]:51377
```

**Comment by pietern** [comment] 2017-05-04 15:06
@talk2ap001 Thanks for testing. This rules out the EINTR path. The problem is that the other side is not reading/acknowledging these bytes for some reason... We can probably "fix" this by putting the communication pairs in asynchronous mode, but I'm interested in finding the underlying cause as well.

There's a tiny change you can do to the Caffe2 code to do this, but I'll reply further in the Caffe2 thread.

**Comment by pietern** [comment] 2017-05-04 22:47
I realize what's going on now:

In async mode all writes are one-sided. A threads kicks off a send on its send buffer, the write(2) call happens, and on the read side the device thread takes care of reading that data into the particular buffer for that pair. It's one-sided in that the receiving end doesn't need to do anything. Switching things out to sync mode makes these operations two-sided. Every time a write happens, a read must happen on the other side, at the same time. If it doesn't, it depends on the TCP buffer size whether or not the operation can continue. If the attempted write is bigger than the TCP buffer size, and its peer isn't doing a read, this write will block indefinitely. It's just that the TCP buffers in our testing have been large enough for everything to appear one-sided. If either the TCP buffers are smaller, or the writes are larger, this breaks down.

The algorithms implemented using the Gloo transport are expecting one-sides operations to be OK. Think of a ring algorithm: all nodes will perform a write and then a read, all in lock step. If the write is too big to fit in a TCP buffer (or the sum of both the sender and receiver TCP buffer), then it deadlocks, because there's nobody to read that data.

This means there is an upper limit of write size proportional to the TCP buffer size where we can use sync mode. Beyond that size, deadlock happens.

The solution for Caffe2 is to switch to async mode by default and make sync mode optional. Additionally, it would be nice to have an error message in Gloo that takes this into account and points to this very issue on GitHub :)

**Comment by sergey-serebryakov** [comment] 2017-05-04 23:06
@pietern Thanks for explanation. Indeed, an error message with a meaningful content would be great. Are there any trade-offs  in sync/async regimes in Caffe2 like communication latency,  memory or CPU consumption?

**Comment by pietern** [comment] 2017-05-04 23:40
@sergey-serebryakov The sync mode has a little bit better latency since it cuts our a context switch between device thread and user thread, but for Caffe2 usage this is marginal enough to not matter.

**Comment by pietern** [comment] 2017-05-04 23:40
And it's only latency btw, nothing else changes (cpu or memory).

**Comment by talk2ap001** [comment] 2017-05-05 06:23
Thanks for the explanation @pietern

**Comment by pietern** [comment] 2017-05-05 16:58
Closing the issue. Updating Caffe2 to **not** use sync mode by default.

**Closed by pietern** 2017-05-05 16:58 UTC
