### ISSUE TITLE
Is possible to run IB benchmark on Ethernet via RoCE?

### ISSUE THREAD

**Issue by royxue** [facebookincubator/gloo#147] opened 2018-11-01 08:51 UTC
I tried to run the benchmark on the 100G Ethernet via RoCE, but it failed with this err.
```
wc->status == IBV_WC_SUCCESS. 5 vs 0. Send for slot 0: Work Request Flushed Error
```

I wonder if it is possible to do this?

**Comment by royxue** [comment] 2018-11-02 02:39
@pietern Yep, I ran the ibv test commands successfully.
But im not sure why it cannot work with benchmark.
I compiled using -DUSE_IBVERBS
and run the benchmark with 
```
  ./benchmark \
  --size 2 \
  --rank 1 \
  --redis-host 192.168.10.100 \
  --redis-port 7777 \
  --prefix 1231231 \
  --transport ibverbs \
  --ib-device qedr0 \
  --elements -1 \
  --iteration-time 10s \
  broadcast_one_to_all
```

**Comment by royxue** [comment] 2018-11-02 03:08
Is this related to RoCE local GID?
As RoCE ping pong need to specify the local gid index to run.

**Comment by pietern** [comment] 2018-11-02 03:15
That is certainly possible. Can you paste the output of `show_gids`?

**Comment by royxue** [comment] 2018-11-02 04:38
Yep, I think maybe this is the cause, my RoCE HPC has 2 gids.
```
DEV	PORT	INDEX	GID					IPv4  		VER	DEV
---	----	-----	---					------------  	---	---
qedr0	1	0	fe80:0000:0000:0000:020e:1eff:fed7:a021
qedr0	1	1	0000:0000:0000:0000:0000:ffff:c0a8:0a64	192.168.10.100
n_gids_found=2
```

**Comment by pietern** [comment] 2018-11-02 05:14
You can check out `benchmark --help` for the default options. By default it uses IB port 1 and IB index 0. The `fe80` prefix on index 0 makes me think it is some kind of link local thing and may be the cause of your problems. Can you try using IB index 1 and see what happens?

**Comment by royxue** [comment] 2018-11-02 06:41
I tried with ib-index 1
it can show some result, but still error occurs.
```
   elements   min (us)   p50 (us)   p99 (us)   max (us)   avg (GB/s)    samples
        100         27         46         75        260        0.008     179836
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/dji/gloo/gloo/transport/ibverbs/pair.cc:437] wc->status == IBV_WC_SUCCESS. 5 vs 0. Send for slot 0: Work Request Flushed Error
Aborted (core dumped)
```

**Comment by pietern** [comment] 2018-11-10 00:01
This is odd... Do you see perhaps one of the other processes crash?

The one line of output indicates that it's working as expected. Once that completes, the benchmark process reinitializes and runs again, so something must be going wrong there...

**Comment by pietern** [comment] 2019-03-07 18:49
No updates for a while. Closing the issue. Feel free to reopen if this is not yet resolved.

**Closed by pietern** 2019-03-07 18:49 UTC

**Comment by royxue** [comment] 2019-03-08 02:03
Sure.
I asked Cisco engineers to look into this problem last time, seems it's the RoCE v2 settings problems.

**Comment by junhuihuang** [comment] 2019-05-22 03:49
Hi @pietern 

I got the same error, but if I disable the below code `ibv_destroy`, the benchmark can work well. 

How do I fix this problem?

Thank you.

file: `gloo/gloo/transport/ibverbs/pair.cc`

```
Pair::~Pair() {
  int rv;

  // Acknowledge number of completion events handled by this
  // pair's completion queue (also see ibv_get_cq_event(3)).
  ibv_ack_cq_events(cq_, completionEventsHandled_);

  // rv = ibv_destroy_qp(qp_);
  // GLOO_ENFORCE_EQ(rv, 0);

  // rv = ibv_destroy_cq(cq_);
  // GLOO_ENFORCE_EQ(rv, 0);
}
```

**Comment by pietern** [comment] 2019-07-22 13:11
@junhuihuang That is very odd... Destroying something that has been created should always succeed?

Did you perhaps see any other errors logged elsewhere?

**Comment by junhuihuang** [comment] 2019-07-23 12:04
Always succeed, no other errors.

Thanks for your reply.

**Comment by pietern** [comment] 2019-07-24 07:18
OK, thanks for confirming.
